// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBProtocol.proto

package com.cat.server.game.data.proto;

public final class PBDefine {
  private PBDefine() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *生成规则
   *请求协议号=模块id*100+请求协议号
   *返回协议号=模块id*100+100+返回协议号
   * </pre>
   *
   * Protobuf enum {@code Protocol.PBProtocol}
   */
  public enum PBProtocol
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *system
     * </pre>
     *
     * <code>UNIVERSAL = 0;</code>
     */
    UNIVERSAL(0),
    /**
     * <pre>
     *common-1
     * </pre>
     *
     * <code>AckTips = 1101;</code>
     */
    AckTips(1101),
    /**
     * <pre>
     *login-100
     * </pre>
     *
     * <code>ReqPlayerLogin = 100001;</code>
     */
    ReqPlayerLogin(100001),
    /**
     * <code>AckPlayerLogin = 100101;</code>
     */
    AckPlayerLogin(100101),
    /**
     * <code>ReqPlayerRandName = 100002;</code>
     */
    ReqPlayerRandName(100002),
    /**
     * <code>AckPlayerRandName = 100102;</code>
     */
    AckPlayerRandName(100102),
    /**
     * <code>ReqPlayerCreateRole = 100003;</code>
     */
    ReqPlayerCreateRole(100003),
    /**
     * <code>AckPlayerCreateRole = 100103;</code>
     */
    AckPlayerCreateRole(100103),
    /**
     * <code>AckPlayerEnterGame = 100104;</code>
     */
    AckPlayerEnterGame(100104),
    /**
     * <code>ReqPlayerReLogin = 100005;</code>
     */
    ReqPlayerReLogin(100005),
    /**
     * <code>AckPlayerReLogin = 100105;</code>
     */
    AckPlayerReLogin(100105),
    /**
     * <code>ReqPlayerHeart = 100006;</code>
     */
    ReqPlayerHeart(100006),
    /**
     * <code>AckPlayerHeart = 100106;</code>
     */
    AckPlayerHeart(100106),
    /**
     * <code>AckPlayerDisconnect = 100107;</code>
     */
    AckPlayerDisconnect(100107),
    /**
     * <code>AckInitPlayerInfo = 100108;</code>
     */
    AckInitPlayerInfo(100108),
    /**
     * <code>AckUpdatePlayerInfo = 100109;</code>
     */
    AckUpdatePlayerInfo(100109),
    /**
     * <pre>
     *chat-101
     * </pre>
     *
     * <code>ReqChat = 101001;</code>
     */
    ReqChat(101001),
    /**
     * <code>AckChat = 101101;</code>
     */
    AckChat(101101),
    /**
     * <pre>
     *item-102
     * </pre>
     *
     * <code>ReqItemUse = 102001;</code>
     */
    ReqItemUse(102001),
    /**
     * <code>AckItemUse = 102101;</code>
     */
    AckItemUse(102101),
    /**
     * <code>ReqItemSell = 102002;</code>
     */
    ReqItemSell(102002),
    /**
     * <code>AckItemSell = 102102;</code>
     */
    AckItemSell(102102),
    /**
     * <code>AckRewards = 102103;</code>
     */
    AckRewards(102103),
    /**
     * <code>AckItemUpdate = 102104;</code>
     */
    AckItemUpdate(102104),
    /**
     * <code>AckItemDelete = 102105;</code>
     */
    AckItemDelete(102105),
    /**
     * <pre>
     *mail-103
     * </pre>
     *
     * <code>ReqMailRead = 103001;</code>
     */
    ReqMailRead(103001),
    /**
     * <code>AckMailRead = 103101;</code>
     */
    AckMailRead(103101),
    /**
     * <code>ReqMailReward = 103002;</code>
     */
    ReqMailReward(103002),
    /**
     * <code>AckMailReward = 103102;</code>
     */
    AckMailReward(103102),
    /**
     * <code>ReqMailDelete = 103003;</code>
     */
    ReqMailDelete(103003),
    /**
     * <code>AckMailDelete = 103103;</code>
     */
    AckMailDelete(103103),
    /**
     * <code>ReqMailList = 103004;</code>
     */
    ReqMailList(103004),
    /**
     * <code>AckMailList = 103104;</code>
     */
    AckMailList(103104),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *system
     * </pre>
     *
     * <code>UNIVERSAL = 0;</code>
     */
    public static final int UNIVERSAL_VALUE = 0;
    /**
     * <pre>
     *common-1
     * </pre>
     *
     * <code>AckTips = 1101;</code>
     */
    public static final int AckTips_VALUE = 1101;
    /**
     * <pre>
     *login-100
     * </pre>
     *
     * <code>ReqPlayerLogin = 100001;</code>
     */
    public static final int ReqPlayerLogin_VALUE = 100001;
    /**
     * <code>AckPlayerLogin = 100101;</code>
     */
    public static final int AckPlayerLogin_VALUE = 100101;
    /**
     * <code>ReqPlayerRandName = 100002;</code>
     */
    public static final int ReqPlayerRandName_VALUE = 100002;
    /**
     * <code>AckPlayerRandName = 100102;</code>
     */
    public static final int AckPlayerRandName_VALUE = 100102;
    /**
     * <code>ReqPlayerCreateRole = 100003;</code>
     */
    public static final int ReqPlayerCreateRole_VALUE = 100003;
    /**
     * <code>AckPlayerCreateRole = 100103;</code>
     */
    public static final int AckPlayerCreateRole_VALUE = 100103;
    /**
     * <code>AckPlayerEnterGame = 100104;</code>
     */
    public static final int AckPlayerEnterGame_VALUE = 100104;
    /**
     * <code>ReqPlayerReLogin = 100005;</code>
     */
    public static final int ReqPlayerReLogin_VALUE = 100005;
    /**
     * <code>AckPlayerReLogin = 100105;</code>
     */
    public static final int AckPlayerReLogin_VALUE = 100105;
    /**
     * <code>ReqPlayerHeart = 100006;</code>
     */
    public static final int ReqPlayerHeart_VALUE = 100006;
    /**
     * <code>AckPlayerHeart = 100106;</code>
     */
    public static final int AckPlayerHeart_VALUE = 100106;
    /**
     * <code>AckPlayerDisconnect = 100107;</code>
     */
    public static final int AckPlayerDisconnect_VALUE = 100107;
    /**
     * <code>AckInitPlayerInfo = 100108;</code>
     */
    public static final int AckInitPlayerInfo_VALUE = 100108;
    /**
     * <code>AckUpdatePlayerInfo = 100109;</code>
     */
    public static final int AckUpdatePlayerInfo_VALUE = 100109;
    /**
     * <pre>
     *chat-101
     * </pre>
     *
     * <code>ReqChat = 101001;</code>
     */
    public static final int ReqChat_VALUE = 101001;
    /**
     * <code>AckChat = 101101;</code>
     */
    public static final int AckChat_VALUE = 101101;
    /**
     * <pre>
     *item-102
     * </pre>
     *
     * <code>ReqItemUse = 102001;</code>
     */
    public static final int ReqItemUse_VALUE = 102001;
    /**
     * <code>AckItemUse = 102101;</code>
     */
    public static final int AckItemUse_VALUE = 102101;
    /**
     * <code>ReqItemSell = 102002;</code>
     */
    public static final int ReqItemSell_VALUE = 102002;
    /**
     * <code>AckItemSell = 102102;</code>
     */
    public static final int AckItemSell_VALUE = 102102;
    /**
     * <code>AckRewards = 102103;</code>
     */
    public static final int AckRewards_VALUE = 102103;
    /**
     * <code>AckItemUpdate = 102104;</code>
     */
    public static final int AckItemUpdate_VALUE = 102104;
    /**
     * <code>AckItemDelete = 102105;</code>
     */
    public static final int AckItemDelete_VALUE = 102105;
    /**
     * <pre>
     *mail-103
     * </pre>
     *
     * <code>ReqMailRead = 103001;</code>
     */
    public static final int ReqMailRead_VALUE = 103001;
    /**
     * <code>AckMailRead = 103101;</code>
     */
    public static final int AckMailRead_VALUE = 103101;
    /**
     * <code>ReqMailReward = 103002;</code>
     */
    public static final int ReqMailReward_VALUE = 103002;
    /**
     * <code>AckMailReward = 103102;</code>
     */
    public static final int AckMailReward_VALUE = 103102;
    /**
     * <code>ReqMailDelete = 103003;</code>
     */
    public static final int ReqMailDelete_VALUE = 103003;
    /**
     * <code>AckMailDelete = 103103;</code>
     */
    public static final int AckMailDelete_VALUE = 103103;
    /**
     * <code>ReqMailList = 103004;</code>
     */
    public static final int ReqMailList_VALUE = 103004;
    /**
     * <code>AckMailList = 103104;</code>
     */
    public static final int AckMailList_VALUE = 103104;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PBProtocol valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PBProtocol forNumber(int value) {
      switch (value) {
        case 0: return UNIVERSAL;
        case 1101: return AckTips;
        case 100001: return ReqPlayerLogin;
        case 100101: return AckPlayerLogin;
        case 100002: return ReqPlayerRandName;
        case 100102: return AckPlayerRandName;
        case 100003: return ReqPlayerCreateRole;
        case 100103: return AckPlayerCreateRole;
        case 100104: return AckPlayerEnterGame;
        case 100005: return ReqPlayerReLogin;
        case 100105: return AckPlayerReLogin;
        case 100006: return ReqPlayerHeart;
        case 100106: return AckPlayerHeart;
        case 100107: return AckPlayerDisconnect;
        case 100108: return AckInitPlayerInfo;
        case 100109: return AckUpdatePlayerInfo;
        case 101001: return ReqChat;
        case 101101: return AckChat;
        case 102001: return ReqItemUse;
        case 102101: return AckItemUse;
        case 102002: return ReqItemSell;
        case 102102: return AckItemSell;
        case 102103: return AckRewards;
        case 102104: return AckItemUpdate;
        case 102105: return AckItemDelete;
        case 103001: return ReqMailRead;
        case 103101: return AckMailRead;
        case 103002: return ReqMailReward;
        case 103102: return AckMailReward;
        case 103003: return ReqMailDelete;
        case 103103: return AckMailDelete;
        case 103004: return ReqMailList;
        case 103104: return AckMailList;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PBProtocol>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PBProtocol> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PBProtocol>() {
            public PBProtocol findValueByNumber(int number) {
              return PBProtocol.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cat.server.game.data.proto.PBDefine.getDescriptor().getEnumTypes().get(0);
    }

    private static final PBProtocol[] VALUES = values();

    public static PBProtocol valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PBProtocol(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Protocol.PBProtocol)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020PBProtocol.proto\022\010Protocol*\306\005\n\nPBProto" +
      "col\022\r\n\tUNIVERSAL\020\000\022\014\n\007AckTips\020\315\010\022\024\n\016ReqP" +
      "layerLogin\020\241\215\006\022\024\n\016AckPlayerLogin\020\205\216\006\022\027\n\021" +
      "ReqPlayerRandName\020\242\215\006\022\027\n\021AckPlayerRandNa" +
      "me\020\206\216\006\022\031\n\023ReqPlayerCreateRole\020\243\215\006\022\031\n\023Ack" +
      "PlayerCreateRole\020\207\216\006\022\030\n\022AckPlayerEnterGa" +
      "me\020\210\216\006\022\026\n\020ReqPlayerReLogin\020\245\215\006\022\026\n\020AckPla" +
      "yerReLogin\020\211\216\006\022\024\n\016ReqPlayerHeart\020\246\215\006\022\024\n\016" +
      "AckPlayerHeart\020\212\216\006\022\031\n\023AckPlayerDisconnec" +
      "t\020\213\216\006\022\027\n\021AckInitPlayerInfo\020\214\216\006\022\031\n\023AckUpd" +
      "atePlayerInfo\020\215\216\006\022\r\n\007ReqChat\020\211\225\006\022\r\n\007AckC" +
      "hat\020\355\225\006\022\020\n\nReqItemUse\020\361\234\006\022\020\n\nAckItemUse\020" +
      "\325\235\006\022\021\n\013ReqItemSell\020\362\234\006\022\021\n\013AckItemSell\020\326\235" +
      "\006\022\020\n\nAckRewards\020\327\235\006\022\023\n\rAckItemUpdate\020\330\235\006" +
      "\022\023\n\rAckItemDelete\020\331\235\006\022\021\n\013ReqMailRead\020\331\244\006" +
      "\022\021\n\013AckMailRead\020\275\245\006\022\023\n\rReqMailReward\020\332\244\006" +
      "\022\023\n\rAckMailReward\020\276\245\006\022\023\n\rReqMailDelete\020\333" +
      "\244\006\022\023\n\rAckMailDelete\020\277\245\006\022\021\n\013ReqMailList\020\334" +
      "\244\006\022\021\n\013AckMailList\020\300\245\006B*\n\036com.cat.server." +
      "game.data.protoB\010PBDefineb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
