// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBCommon.proto

package com.cat.server.game.data.proto;

public final class PBCommon {
  private PBCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AckTipsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protocol.AckTips)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 tipsId = 1;</code>
     * @return The tipsId.
     */
    int getTipsId();

    /**
     * <code>repeated int32 params = 2;</code>
     * @return A list containing the params.
     */
    java.util.List<java.lang.Integer> getParamsList();
    /**
     * <code>repeated int32 params = 2;</code>
     * @return The count of params.
     */
    int getParamsCount();
    /**
     * <code>repeated int32 params = 2;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    int getParams(int index);
  }
  /**
   * <pre>
   *tips信息
   * </pre>
   *
   * Protobuf type {@code Protocol.AckTips}
   */
  public  static final class AckTips extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protocol.AckTips)
      AckTipsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AckTips.newBuilder() to construct.
    private AckTips(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AckTips() {
      params_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AckTips();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AckTips(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              tipsId_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                params_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              params_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                params_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                params_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          params_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cat.server.game.data.proto.PBCommon.internal_static_Protocol_AckTips_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cat.server.game.data.proto.PBCommon.internal_static_Protocol_AckTips_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cat.server.game.data.proto.PBCommon.AckTips.class, com.cat.server.game.data.proto.PBCommon.AckTips.Builder.class);
    }

    public static final int TIPSID_FIELD_NUMBER = 1;
    private int tipsId_;
    /**
     * <code>int32 tipsId = 1;</code>
     * @return The tipsId.
     */
    public int getTipsId() {
      return tipsId_;
    }

    public static final int PARAMS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList params_;
    /**
     * <code>repeated int32 params = 2;</code>
     * @return A list containing the params.
     */
    public java.util.List<java.lang.Integer>
        getParamsList() {
      return params_;
    }
    /**
     * <code>repeated int32 params = 2;</code>
     * @return The count of params.
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated int32 params = 2;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    public int getParams(int index) {
      return params_.getInt(index);
    }
    private int paramsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (tipsId_ != 0) {
        output.writeInt32(1, tipsId_);
      }
      if (getParamsList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(paramsMemoizedSerializedSize);
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeInt32NoTag(params_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tipsId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, tipsId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(params_.getInt(i));
        }
        size += dataSize;
        if (!getParamsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        paramsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cat.server.game.data.proto.PBCommon.AckTips)) {
        return super.equals(obj);
      }
      com.cat.server.game.data.proto.PBCommon.AckTips other = (com.cat.server.game.data.proto.PBCommon.AckTips) obj;

      if (getTipsId()
          != other.getTipsId()) return false;
      if (!getParamsList()
          .equals(other.getParamsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIPSID_FIELD_NUMBER;
      hash = (53 * hash) + getTipsId();
      if (getParamsCount() > 0) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParamsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cat.server.game.data.proto.PBCommon.AckTips parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cat.server.game.data.proto.PBCommon.AckTips parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBCommon.AckTips parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cat.server.game.data.proto.PBCommon.AckTips parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBCommon.AckTips parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cat.server.game.data.proto.PBCommon.AckTips parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBCommon.AckTips parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cat.server.game.data.proto.PBCommon.AckTips parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBCommon.AckTips parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cat.server.game.data.proto.PBCommon.AckTips parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBCommon.AckTips parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cat.server.game.data.proto.PBCommon.AckTips parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cat.server.game.data.proto.PBCommon.AckTips prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *tips信息
     * </pre>
     *
     * Protobuf type {@code Protocol.AckTips}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protocol.AckTips)
        com.cat.server.game.data.proto.PBCommon.AckTipsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cat.server.game.data.proto.PBCommon.internal_static_Protocol_AckTips_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cat.server.game.data.proto.PBCommon.internal_static_Protocol_AckTips_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cat.server.game.data.proto.PBCommon.AckTips.class, com.cat.server.game.data.proto.PBCommon.AckTips.Builder.class);
      }

      // Construct using com.cat.server.game.data.proto.PBCommon.AckTips.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tipsId_ = 0;

        params_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cat.server.game.data.proto.PBCommon.internal_static_Protocol_AckTips_descriptor;
      }

      @java.lang.Override
      public com.cat.server.game.data.proto.PBCommon.AckTips getDefaultInstanceForType() {
        return com.cat.server.game.data.proto.PBCommon.AckTips.getDefaultInstance();
      }

      @java.lang.Override
      public com.cat.server.game.data.proto.PBCommon.AckTips build() {
        com.cat.server.game.data.proto.PBCommon.AckTips result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cat.server.game.data.proto.PBCommon.AckTips buildPartial() {
        com.cat.server.game.data.proto.PBCommon.AckTips result = new com.cat.server.game.data.proto.PBCommon.AckTips(this);
        int from_bitField0_ = bitField0_;
        result.tipsId_ = tipsId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          params_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.params_ = params_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cat.server.game.data.proto.PBCommon.AckTips) {
          return mergeFrom((com.cat.server.game.data.proto.PBCommon.AckTips)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cat.server.game.data.proto.PBCommon.AckTips other) {
        if (other == com.cat.server.game.data.proto.PBCommon.AckTips.getDefaultInstance()) return this;
        if (other.getTipsId() != 0) {
          setTipsId(other.getTipsId());
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cat.server.game.data.proto.PBCommon.AckTips parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cat.server.game.data.proto.PBCommon.AckTips) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int tipsId_ ;
      /**
       * <code>int32 tipsId = 1;</code>
       * @return The tipsId.
       */
      public int getTipsId() {
        return tipsId_;
      }
      /**
       * <code>int32 tipsId = 1;</code>
       * @param value The tipsId to set.
       * @return This builder for chaining.
       */
      public Builder setTipsId(int value) {
        
        tipsId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 tipsId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTipsId() {
        
        tipsId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList params_ = emptyIntList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          params_ = mutableCopy(params_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 params = 2;</code>
       * @return A list containing the params.
       */
      public java.util.List<java.lang.Integer>
          getParamsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(params_) : params_;
      }
      /**
       * <code>repeated int32 params = 2;</code>
       * @return The count of params.
       */
      public int getParamsCount() {
        return params_.size();
      }
      /**
       * <code>repeated int32 params = 2;</code>
       * @param index The index of the element to return.
       * @return The params at the given index.
       */
      public int getParams(int index) {
        return params_.getInt(index);
      }
      /**
       * <code>repeated int32 params = 2;</code>
       * @param index The index to set the value at.
       * @param value The params to set.
       * @return This builder for chaining.
       */
      public Builder setParams(
          int index, int value) {
        ensureParamsIsMutable();
        params_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 params = 2;</code>
       * @param value The params to add.
       * @return This builder for chaining.
       */
      public Builder addParams(int value) {
        ensureParamsIsMutable();
        params_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 params = 2;</code>
       * @param values The params to add.
       * @return This builder for chaining.
       */
      public Builder addAllParams(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureParamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, params_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 params = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearParams() {
        params_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protocol.AckTips)
    }

    // @@protoc_insertion_point(class_scope:Protocol.AckTips)
    private static final com.cat.server.game.data.proto.PBCommon.AckTips DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cat.server.game.data.proto.PBCommon.AckTips();
    }

    public static com.cat.server.game.data.proto.PBCommon.AckTips getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AckTips>
        PARSER = new com.google.protobuf.AbstractParser<AckTips>() {
      @java.lang.Override
      public AckTips parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AckTips(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AckTips> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AckTips> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cat.server.game.data.proto.PBCommon.AckTips getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocol_AckTips_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocol_AckTips_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016PBCommon.proto\022\010Protocol\")\n\007AckTips\022\016\n" +
      "\006tipsId\030\001 \001(\005\022\016\n\006params\030\002 \003(\005B*\n\036com.cat" +
      ".server.game.data.protoB\010PBCommonb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Protocol_AckTips_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protocol_AckTips_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocol_AckTips_descriptor,
        new java.lang.String[] { "TipsId", "Params", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
