// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBFunctionControl.proto

package com.cat.server.game.data.proto;

public final class PBFunctionControl {
  private PBFunctionControl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqFunctionControlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protocol.ReqFunctionControl)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 请求功能控制信息
   * </pre>
   *
   * Protobuf type {@code Protocol.ReqFunctionControl}
   */
  public  static final class ReqFunctionControl extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protocol.ReqFunctionControl)
      ReqFunctionControlOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqFunctionControl.newBuilder() to construct.
    private ReqFunctionControl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqFunctionControl() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReqFunctionControl();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqFunctionControl(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_ReqFunctionControl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_ReqFunctionControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl.class, com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl)) {
        return super.equals(obj);
      }
      com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl other = (com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求功能控制信息
     * </pre>
     *
     * Protobuf type {@code Protocol.ReqFunctionControl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protocol.ReqFunctionControl)
        com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_ReqFunctionControl_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_ReqFunctionControl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl.class, com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl.Builder.class);
      }

      // Construct using com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_ReqFunctionControl_descriptor;
      }

      @java.lang.Override
      public com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl getDefaultInstanceForType() {
        return com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl.getDefaultInstance();
      }

      @java.lang.Override
      public com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl build() {
        com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl buildPartial() {
        com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl result = new com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl) {
          return mergeFrom((com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl other) {
        if (other == com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protocol.ReqFunctionControl)
    }

    // @@protoc_insertion_point(class_scope:Protocol.ReqFunctionControl)
    private static final com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl();
    }

    public static com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqFunctionControl>
        PARSER = new com.google.protobuf.AbstractParser<ReqFunctionControl>() {
      @java.lang.Override
      public ReqFunctionControl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqFunctionControl(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqFunctionControl> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqFunctionControl> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cat.server.game.data.proto.PBFunctionControl.ReqFunctionControl getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResFunctionControlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protocol.ResFunctionControl)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *功能信息
     * </pre>
     *
     * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
     */
    java.util.List<com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo> 
        getFunctionInfoList();
    /**
     * <pre>
     *功能信息
     * </pre>
     *
     * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
     */
    com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo getFunctionInfo(int index);
    /**
     * <pre>
     *功能信息
     * </pre>
     *
     * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
     */
    int getFunctionInfoCount();
    /**
     * <pre>
     *功能信息
     * </pre>
     *
     * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
     */
    java.util.List<? extends com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfoOrBuilder> 
        getFunctionInfoOrBuilderList();
    /**
     * <pre>
     *功能信息
     * </pre>
     *
     * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
     */
    com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfoOrBuilder getFunctionInfoOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 响应功能控制信息
   * </pre>
   *
   * Protobuf type {@code Protocol.ResFunctionControl}
   */
  public  static final class ResFunctionControl extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protocol.ResFunctionControl)
      ResFunctionControlOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResFunctionControl.newBuilder() to construct.
    private ResFunctionControl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResFunctionControl() {
      functionInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResFunctionControl();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResFunctionControl(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                functionInfo_ = new java.util.ArrayList<com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              functionInfo_.add(
                  input.readMessage(com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          functionInfo_ = java.util.Collections.unmodifiableList(functionInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_ResFunctionControl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_ResFunctionControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl.class, com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl.Builder.class);
    }

    public static final int FUNCTIONINFO_FIELD_NUMBER = 1;
    private java.util.List<com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo> functionInfo_;
    /**
     * <pre>
     *功能信息
     * </pre>
     *
     * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
     */
    public java.util.List<com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo> getFunctionInfoList() {
      return functionInfo_;
    }
    /**
     * <pre>
     *功能信息
     * </pre>
     *
     * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
     */
    public java.util.List<? extends com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfoOrBuilder> 
        getFunctionInfoOrBuilderList() {
      return functionInfo_;
    }
    /**
     * <pre>
     *功能信息
     * </pre>
     *
     * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
     */
    public int getFunctionInfoCount() {
      return functionInfo_.size();
    }
    /**
     * <pre>
     *功能信息
     * </pre>
     *
     * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
     */
    public com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo getFunctionInfo(int index) {
      return functionInfo_.get(index);
    }
    /**
     * <pre>
     *功能信息
     * </pre>
     *
     * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
     */
    public com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfoOrBuilder getFunctionInfoOrBuilder(
        int index) {
      return functionInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < functionInfo_.size(); i++) {
        output.writeMessage(1, functionInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < functionInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, functionInfo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl)) {
        return super.equals(obj);
      }
      com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl other = (com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl) obj;

      if (!getFunctionInfoList()
          .equals(other.getFunctionInfoList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFunctionInfoCount() > 0) {
        hash = (37 * hash) + FUNCTIONINFO_FIELD_NUMBER;
        hash = (53 * hash) + getFunctionInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 响应功能控制信息
     * </pre>
     *
     * Protobuf type {@code Protocol.ResFunctionControl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protocol.ResFunctionControl)
        com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_ResFunctionControl_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_ResFunctionControl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl.class, com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl.Builder.class);
      }

      // Construct using com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFunctionInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (functionInfoBuilder_ == null) {
          functionInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          functionInfoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_ResFunctionControl_descriptor;
      }

      @java.lang.Override
      public com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl getDefaultInstanceForType() {
        return com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl.getDefaultInstance();
      }

      @java.lang.Override
      public com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl build() {
        com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl buildPartial() {
        com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl result = new com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl(this);
        int from_bitField0_ = bitField0_;
        if (functionInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            functionInfo_ = java.util.Collections.unmodifiableList(functionInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.functionInfo_ = functionInfo_;
        } else {
          result.functionInfo_ = functionInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl) {
          return mergeFrom((com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl other) {
        if (other == com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl.getDefaultInstance()) return this;
        if (functionInfoBuilder_ == null) {
          if (!other.functionInfo_.isEmpty()) {
            if (functionInfo_.isEmpty()) {
              functionInfo_ = other.functionInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFunctionInfoIsMutable();
              functionInfo_.addAll(other.functionInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.functionInfo_.isEmpty()) {
            if (functionInfoBuilder_.isEmpty()) {
              functionInfoBuilder_.dispose();
              functionInfoBuilder_ = null;
              functionInfo_ = other.functionInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              functionInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFunctionInfoFieldBuilder() : null;
            } else {
              functionInfoBuilder_.addAllMessages(other.functionInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo> functionInfo_ =
        java.util.Collections.emptyList();
      private void ensureFunctionInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          functionInfo_ = new java.util.ArrayList<com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo>(functionInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.Builder, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfoOrBuilder> functionInfoBuilder_;

      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public java.util.List<com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo> getFunctionInfoList() {
        if (functionInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(functionInfo_);
        } else {
          return functionInfoBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public int getFunctionInfoCount() {
        if (functionInfoBuilder_ == null) {
          return functionInfo_.size();
        } else {
          return functionInfoBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo getFunctionInfo(int index) {
        if (functionInfoBuilder_ == null) {
          return functionInfo_.get(index);
        } else {
          return functionInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public Builder setFunctionInfo(
          int index, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo value) {
        if (functionInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFunctionInfoIsMutable();
          functionInfo_.set(index, value);
          onChanged();
        } else {
          functionInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public Builder setFunctionInfo(
          int index, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.Builder builderForValue) {
        if (functionInfoBuilder_ == null) {
          ensureFunctionInfoIsMutable();
          functionInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          functionInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public Builder addFunctionInfo(com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo value) {
        if (functionInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFunctionInfoIsMutable();
          functionInfo_.add(value);
          onChanged();
        } else {
          functionInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public Builder addFunctionInfo(
          int index, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo value) {
        if (functionInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFunctionInfoIsMutable();
          functionInfo_.add(index, value);
          onChanged();
        } else {
          functionInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public Builder addFunctionInfo(
          com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.Builder builderForValue) {
        if (functionInfoBuilder_ == null) {
          ensureFunctionInfoIsMutable();
          functionInfo_.add(builderForValue.build());
          onChanged();
        } else {
          functionInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public Builder addFunctionInfo(
          int index, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.Builder builderForValue) {
        if (functionInfoBuilder_ == null) {
          ensureFunctionInfoIsMutable();
          functionInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          functionInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public Builder addAllFunctionInfo(
          java.lang.Iterable<? extends com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo> values) {
        if (functionInfoBuilder_ == null) {
          ensureFunctionInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, functionInfo_);
          onChanged();
        } else {
          functionInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public Builder clearFunctionInfo() {
        if (functionInfoBuilder_ == null) {
          functionInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          functionInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public Builder removeFunctionInfo(int index) {
        if (functionInfoBuilder_ == null) {
          ensureFunctionInfoIsMutable();
          functionInfo_.remove(index);
          onChanged();
        } else {
          functionInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.Builder getFunctionInfoBuilder(
          int index) {
        return getFunctionInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfoOrBuilder getFunctionInfoOrBuilder(
          int index) {
        if (functionInfoBuilder_ == null) {
          return functionInfo_.get(index);  } else {
          return functionInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public java.util.List<? extends com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfoOrBuilder> 
           getFunctionInfoOrBuilderList() {
        if (functionInfoBuilder_ != null) {
          return functionInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(functionInfo_);
        }
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.Builder addFunctionInfoBuilder() {
        return getFunctionInfoFieldBuilder().addBuilder(
            com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.getDefaultInstance());
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.Builder addFunctionInfoBuilder(
          int index) {
        return getFunctionInfoFieldBuilder().addBuilder(
            index, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.getDefaultInstance());
      }
      /**
       * <pre>
       *功能信息
       * </pre>
       *
       * <code>repeated .Protocol.PBFunctionInfo functionInfo = 1;</code>
       */
      public java.util.List<com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.Builder> 
           getFunctionInfoBuilderList() {
        return getFunctionInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.Builder, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfoOrBuilder> 
          getFunctionInfoFieldBuilder() {
        if (functionInfoBuilder_ == null) {
          functionInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.Builder, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfoOrBuilder>(
                  functionInfo_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          functionInfo_ = null;
        }
        return functionInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protocol.ResFunctionControl)
    }

    // @@protoc_insertion_point(class_scope:Protocol.ResFunctionControl)
    private static final com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl();
    }

    public static com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResFunctionControl>
        PARSER = new com.google.protobuf.AbstractParser<ResFunctionControl>() {
      @java.lang.Override
      public ResFunctionControl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResFunctionControl(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResFunctionControl> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResFunctionControl> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cat.server.game.data.proto.PBFunctionControl.ResFunctionControl getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PBFunctionInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protocol.PBFunctionInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *功能模块id
     * </pre>
     *
     * <code>int32 functionId = 1;</code>
     * @return The functionId.
     */
    int getFunctionId();

    /**
     * <pre>
     *是否开启
     * </pre>
     *
     * <code>int32 open = 2;</code>
     * @return The open.
     */
    int getOpen();
  }
  /**
   * <pre>
   * 功能信息
   * </pre>
   *
   * Protobuf type {@code Protocol.PBFunctionInfo}
   */
  public  static final class PBFunctionInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protocol.PBFunctionInfo)
      PBFunctionInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PBFunctionInfo.newBuilder() to construct.
    private PBFunctionInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBFunctionInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PBFunctionInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBFunctionInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              functionId_ = input.readInt32();
              break;
            }
            case 16: {

              open_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_PBFunctionInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_PBFunctionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.class, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.Builder.class);
    }

    public static final int FUNCTIONID_FIELD_NUMBER = 1;
    private int functionId_;
    /**
     * <pre>
     *功能模块id
     * </pre>
     *
     * <code>int32 functionId = 1;</code>
     * @return The functionId.
     */
    public int getFunctionId() {
      return functionId_;
    }

    public static final int OPEN_FIELD_NUMBER = 2;
    private int open_;
    /**
     * <pre>
     *是否开启
     * </pre>
     *
     * <code>int32 open = 2;</code>
     * @return The open.
     */
    public int getOpen() {
      return open_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (functionId_ != 0) {
        output.writeInt32(1, functionId_);
      }
      if (open_ != 0) {
        output.writeInt32(2, open_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (functionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, functionId_);
      }
      if (open_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, open_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo)) {
        return super.equals(obj);
      }
      com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo other = (com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo) obj;

      if (getFunctionId()
          != other.getFunctionId()) return false;
      if (getOpen()
          != other.getOpen()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FUNCTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getFunctionId();
      hash = (37 * hash) + OPEN_FIELD_NUMBER;
      hash = (53 * hash) + getOpen();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 功能信息
     * </pre>
     *
     * Protobuf type {@code Protocol.PBFunctionInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protocol.PBFunctionInfo)
        com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_PBFunctionInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_PBFunctionInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.class, com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.Builder.class);
      }

      // Construct using com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        functionId_ = 0;

        open_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cat.server.game.data.proto.PBFunctionControl.internal_static_Protocol_PBFunctionInfo_descriptor;
      }

      @java.lang.Override
      public com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo getDefaultInstanceForType() {
        return com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo build() {
        com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo buildPartial() {
        com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo result = new com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo(this);
        result.functionId_ = functionId_;
        result.open_ = open_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo) {
          return mergeFrom((com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo other) {
        if (other == com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo.getDefaultInstance()) return this;
        if (other.getFunctionId() != 0) {
          setFunctionId(other.getFunctionId());
        }
        if (other.getOpen() != 0) {
          setOpen(other.getOpen());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int functionId_ ;
      /**
       * <pre>
       *功能模块id
       * </pre>
       *
       * <code>int32 functionId = 1;</code>
       * @return The functionId.
       */
      public int getFunctionId() {
        return functionId_;
      }
      /**
       * <pre>
       *功能模块id
       * </pre>
       *
       * <code>int32 functionId = 1;</code>
       * @param value The functionId to set.
       * @return This builder for chaining.
       */
      public Builder setFunctionId(int value) {
        
        functionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *功能模块id
       * </pre>
       *
       * <code>int32 functionId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFunctionId() {
        
        functionId_ = 0;
        onChanged();
        return this;
      }

      private int open_ ;
      /**
       * <pre>
       *是否开启
       * </pre>
       *
       * <code>int32 open = 2;</code>
       * @return The open.
       */
      public int getOpen() {
        return open_;
      }
      /**
       * <pre>
       *是否开启
       * </pre>
       *
       * <code>int32 open = 2;</code>
       * @param value The open to set.
       * @return This builder for chaining.
       */
      public Builder setOpen(int value) {
        
        open_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否开启
       * </pre>
       *
       * <code>int32 open = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpen() {
        
        open_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protocol.PBFunctionInfo)
    }

    // @@protoc_insertion_point(class_scope:Protocol.PBFunctionInfo)
    private static final com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo();
    }

    public static com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PBFunctionInfo>
        PARSER = new com.google.protobuf.AbstractParser<PBFunctionInfo>() {
      @java.lang.Override
      public PBFunctionInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBFunctionInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBFunctionInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBFunctionInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cat.server.game.data.proto.PBFunctionControl.PBFunctionInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocol_ReqFunctionControl_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocol_ReqFunctionControl_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocol_ResFunctionControl_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocol_ResFunctionControl_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocol_PBFunctionInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocol_PBFunctionInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027PBFunctionControl.proto\022\010Protocol\"\024\n\022R" +
      "eqFunctionControl\"D\n\022ResFunctionControl\022" +
      ".\n\014functionInfo\030\001 \003(\0132\030.Protocol.PBFunct" +
      "ionInfo\"2\n\016PBFunctionInfo\022\022\n\nfunctionId\030" +
      "\001 \001(\005\022\014\n\004open\030\002 \001(\005B3\n\036com.cat.server.ga" +
      "me.data.protoB\021PBFunctionControlb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Protocol_ReqFunctionControl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protocol_ReqFunctionControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocol_ReqFunctionControl_descriptor,
        new java.lang.String[] { });
    internal_static_Protocol_ResFunctionControl_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protocol_ResFunctionControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocol_ResFunctionControl_descriptor,
        new java.lang.String[] { "FunctionInfo", });
    internal_static_Protocol_PBFunctionInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Protocol_PBFunctionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocol_PBFunctionInfo_descriptor,
        new java.lang.String[] { "FunctionId", "Open", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
