// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Proto.PetMessage {

  /// <summary>Holder for reflection information generated from pet.proto</summary>
  public static partial class PetReflection {

    #region Descriptor
    /// <summary>File descriptor for pet.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PetReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglwZXQucHJvdG8SFGNvbS5wcm90by5wZXRNZXNzYWdlIhEKD1JlcVBldElu",
            "Zm9Qcm90byIxChpSZXFQZXRJbmN1YmF0b3JVbmxvY2tQcm90bxITCgtpbmN1",
            "YmF0b3JJZBgBIAEoBSI0Ch1SZXFQZXRJbmN1YmF0ZUFjY2VsZXJhdGVQcm90",
            "bxITCgtpbmN1YmF0b3JJZBgBIAEoBSIqChNSZXFQZXRTbWFzaEVnZ1Byb3Rv",
            "EhMKC2luY3ViYXRvcklkGAEgASgFIjAKElJlcVBldFVwTGV2ZWxQcm90bxIN",
            "CgVwZXRJZBgBIAEoBRILCgNudW0YAiABKAUiIwoSUmVxUGV0VXBTdGFnZVBy",
            "b3RvEg0KBXBldElkGAEgASgFIiAKD1JlcVBldFNob3dQcm90bxINCgVwZXRJ",
            "ZBgBIAEoBSKVAQoPUmVzUGV0SW5mb1Byb3RvEi8KBHBldHMYASADKAsyIS5j",
            "b20ucHJvdG8ucGV0TWVzc2FnZS5QZXREdG9Qcm90bxI+CgppbmN1YmF0b3Jz",
            "GAIgAygLMiouY29tLnByb3RvLnBldE1lc3NhZ2UuUGV0SW5jdWJhdG9yRHRv",
            "UHJvdG8SEQoJc2hvd1BldElkGAMgASgFIkMKEVJlc1BldFVwZGF0ZVByb3Rv",
            "Ei4KA3BldBgBIAEoCzIhLmNvbS5wcm90by5wZXRNZXNzYWdlLlBldER0b1By",
            "b3RvIlwKGlJlc1BldEluY3ViYXRvclVwZGF0ZVByb3RvEj4KCmluY3ViYXRv",
            "cnMYASADKAsyKi5jb20ucHJvdG8ucGV0TWVzc2FnZS5QZXRJbmN1YmF0b3JE",
            "dG9Qcm90byIzChVSZXNQZXRSZXBlYXRHYWluUHJvdG8SDQoFcGV0SWQYASAB",
            "KAUSCwoDbnVtGAIgASgFIkkKC1BldER0b1Byb3RvEg0KBXBldElkGAEgASgF",
            "Eg0KBXN0YWdlGAIgASgFEg0KBWxldmVsGAMgASgFEg0KBWNvdW50GAQgASgF",
            "Il4KFFBldEluY3ViYXRvckR0b1Byb3RvEhMKC2luY3ViYXRvcklkGAEgASgF",
            "Eg0KBWVnZ0lkGAIgASgFEhEKCXN0YXJ0VGltZRgDIAEoBRIPCgdlbmRUaW1l",
            "GAQgASgFQikKHGNvbS5nYW1lLm1vZHVsZS5wZXQucHJvdG9jb2xCCVBldFBy",
            "b3Rvc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.ReqPetInfoProto), global::Com.Proto.PetMessage.ReqPetInfoProto.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.ReqPetIncubatorUnlockProto), global::Com.Proto.PetMessage.ReqPetIncubatorUnlockProto.Parser, new[]{ "IncubatorId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.ReqPetIncubateAccelerateProto), global::Com.Proto.PetMessage.ReqPetIncubateAccelerateProto.Parser, new[]{ "IncubatorId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.ReqPetSmashEggProto), global::Com.Proto.PetMessage.ReqPetSmashEggProto.Parser, new[]{ "IncubatorId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.ReqPetUpLevelProto), global::Com.Proto.PetMessage.ReqPetUpLevelProto.Parser, new[]{ "PetId", "Num" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.ReqPetUpStageProto), global::Com.Proto.PetMessage.ReqPetUpStageProto.Parser, new[]{ "PetId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.ReqPetShowProto), global::Com.Proto.PetMessage.ReqPetShowProto.Parser, new[]{ "PetId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.ResPetInfoProto), global::Com.Proto.PetMessage.ResPetInfoProto.Parser, new[]{ "Pets", "Incubators", "ShowPetId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.ResPetUpdateProto), global::Com.Proto.PetMessage.ResPetUpdateProto.Parser, new[]{ "Pet" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.ResPetIncubatorUpdateProto), global::Com.Proto.PetMessage.ResPetIncubatorUpdateProto.Parser, new[]{ "Incubators" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.ResPetRepeatGainProto), global::Com.Proto.PetMessage.ResPetRepeatGainProto.Parser, new[]{ "PetId", "Num" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.PetDtoProto), global::Com.Proto.PetMessage.PetDtoProto.Parser, new[]{ "PetId", "Stage", "Level", "Count" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.PetMessage.PetIncubatorDtoProto), global::Com.Proto.PetMessage.PetIncubatorDtoProto.Parser, new[]{ "IncubatorId", "EggId", "StartTime", "EndTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 协议列表
  /// 获取宠物模块信息		msgId=167001
  /// </summary>
  public sealed partial class ReqPetInfoProto : pb::IMessage<ReqPetInfoProto> {
    private static readonly pb::MessageParser<ReqPetInfoProto> _parser = new pb::MessageParser<ReqPetInfoProto>(() => new ReqPetInfoProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqPetInfoProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetInfoProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetInfoProto(ReqPetInfoProto other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetInfoProto Clone() {
      return new ReqPetInfoProto(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqPetInfoProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqPetInfoProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqPetInfoProto other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  /// <summary>
  /// 请求解锁宠物孵蛋机		msgId=167002
  /// </summary>
  public sealed partial class ReqPetIncubatorUnlockProto : pb::IMessage<ReqPetIncubatorUnlockProto> {
    private static readonly pb::MessageParser<ReqPetIncubatorUnlockProto> _parser = new pb::MessageParser<ReqPetIncubatorUnlockProto>(() => new ReqPetIncubatorUnlockProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqPetIncubatorUnlockProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetIncubatorUnlockProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetIncubatorUnlockProto(ReqPetIncubatorUnlockProto other) : this() {
      incubatorId_ = other.incubatorId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetIncubatorUnlockProto Clone() {
      return new ReqPetIncubatorUnlockProto(this);
    }

    /// <summary>Field number for the "incubatorId" field.</summary>
    public const int IncubatorIdFieldNumber = 1;
    private int incubatorId_;
    /// <summary>
    ///孵蛋机id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IncubatorId {
      get { return incubatorId_; }
      set {
        incubatorId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqPetIncubatorUnlockProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqPetIncubatorUnlockProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IncubatorId != other.IncubatorId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IncubatorId != 0) hash ^= IncubatorId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IncubatorId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IncubatorId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IncubatorId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IncubatorId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqPetIncubatorUnlockProto other) {
      if (other == null) {
        return;
      }
      if (other.IncubatorId != 0) {
        IncubatorId = other.IncubatorId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IncubatorId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求宠物加速孵化		msgId=167003
  /// </summary>
  public sealed partial class ReqPetIncubateAccelerateProto : pb::IMessage<ReqPetIncubateAccelerateProto> {
    private static readonly pb::MessageParser<ReqPetIncubateAccelerateProto> _parser = new pb::MessageParser<ReqPetIncubateAccelerateProto>(() => new ReqPetIncubateAccelerateProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqPetIncubateAccelerateProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetIncubateAccelerateProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetIncubateAccelerateProto(ReqPetIncubateAccelerateProto other) : this() {
      incubatorId_ = other.incubatorId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetIncubateAccelerateProto Clone() {
      return new ReqPetIncubateAccelerateProto(this);
    }

    /// <summary>Field number for the "incubatorId" field.</summary>
    public const int IncubatorIdFieldNumber = 1;
    private int incubatorId_;
    /// <summary>
    ///加速的孵蛋器id(-1全部加速)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IncubatorId {
      get { return incubatorId_; }
      set {
        incubatorId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqPetIncubateAccelerateProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqPetIncubateAccelerateProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IncubatorId != other.IncubatorId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IncubatorId != 0) hash ^= IncubatorId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IncubatorId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IncubatorId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IncubatorId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IncubatorId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqPetIncubateAccelerateProto other) {
      if (other == null) {
        return;
      }
      if (other.IncubatorId != 0) {
        IncubatorId = other.IncubatorId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IncubatorId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求砸宠物蛋		msgId=167004
  /// </summary>
  public sealed partial class ReqPetSmashEggProto : pb::IMessage<ReqPetSmashEggProto> {
    private static readonly pb::MessageParser<ReqPetSmashEggProto> _parser = new pb::MessageParser<ReqPetSmashEggProto>(() => new ReqPetSmashEggProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqPetSmashEggProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetSmashEggProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetSmashEggProto(ReqPetSmashEggProto other) : this() {
      incubatorId_ = other.incubatorId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetSmashEggProto Clone() {
      return new ReqPetSmashEggProto(this);
    }

    /// <summary>Field number for the "incubatorId" field.</summary>
    public const int IncubatorIdFieldNumber = 1;
    private int incubatorId_;
    /// <summary>
    ///孵蛋器id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IncubatorId {
      get { return incubatorId_; }
      set {
        incubatorId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqPetSmashEggProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqPetSmashEggProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IncubatorId != other.IncubatorId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IncubatorId != 0) hash ^= IncubatorId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IncubatorId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IncubatorId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IncubatorId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IncubatorId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqPetSmashEggProto other) {
      if (other == null) {
        return;
      }
      if (other.IncubatorId != 0) {
        IncubatorId = other.IncubatorId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IncubatorId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求升级宠物		msgId=167005
  /// </summary>
  public sealed partial class ReqPetUpLevelProto : pb::IMessage<ReqPetUpLevelProto> {
    private static readonly pb::MessageParser<ReqPetUpLevelProto> _parser = new pb::MessageParser<ReqPetUpLevelProto>(() => new ReqPetUpLevelProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqPetUpLevelProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetUpLevelProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetUpLevelProto(ReqPetUpLevelProto other) : this() {
      petId_ = other.petId_;
      num_ = other.num_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetUpLevelProto Clone() {
      return new ReqPetUpLevelProto(this);
    }

    /// <summary>Field number for the "petId" field.</summary>
    public const int PetIdFieldNumber = 1;
    private int petId_;
    /// <summary>
    ///宠物id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PetId {
      get { return petId_; }
      set {
        petId_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 2;
    private int num_;
    /// <summary>
    ///升级次数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqPetUpLevelProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqPetUpLevelProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PetId != other.PetId) return false;
      if (Num != other.Num) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PetId != 0) hash ^= PetId.GetHashCode();
      if (Num != 0) hash ^= Num.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PetId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PetId);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PetId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PetId);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqPetUpLevelProto other) {
      if (other == null) {
        return;
      }
      if (other.PetId != 0) {
        PetId = other.PetId;
      }
      if (other.Num != 0) {
        Num = other.Num;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PetId = input.ReadInt32();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求升阶宠物		msgId=167006
  /// </summary>
  public sealed partial class ReqPetUpStageProto : pb::IMessage<ReqPetUpStageProto> {
    private static readonly pb::MessageParser<ReqPetUpStageProto> _parser = new pb::MessageParser<ReqPetUpStageProto>(() => new ReqPetUpStageProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqPetUpStageProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetUpStageProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetUpStageProto(ReqPetUpStageProto other) : this() {
      petId_ = other.petId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetUpStageProto Clone() {
      return new ReqPetUpStageProto(this);
    }

    /// <summary>Field number for the "petId" field.</summary>
    public const int PetIdFieldNumber = 1;
    private int petId_;
    /// <summary>
    ///宠物id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PetId {
      get { return petId_; }
      set {
        petId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqPetUpStageProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqPetUpStageProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PetId != other.PetId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PetId != 0) hash ^= PetId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PetId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PetId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PetId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PetId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqPetUpStageProto other) {
      if (other == null) {
        return;
      }
      if (other.PetId != 0) {
        PetId = other.PetId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PetId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求设置显示的宠物		msgId=167007
  /// </summary>
  public sealed partial class ReqPetShowProto : pb::IMessage<ReqPetShowProto> {
    private static readonly pb::MessageParser<ReqPetShowProto> _parser = new pb::MessageParser<ReqPetShowProto>(() => new ReqPetShowProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqPetShowProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetShowProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetShowProto(ReqPetShowProto other) : this() {
      petId_ = other.petId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqPetShowProto Clone() {
      return new ReqPetShowProto(this);
    }

    /// <summary>Field number for the "petId" field.</summary>
    public const int PetIdFieldNumber = 1;
    private int petId_;
    /// <summary>
    ///宠物id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PetId {
      get { return petId_; }
      set {
        petId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqPetShowProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqPetShowProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PetId != other.PetId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PetId != 0) hash ^= PetId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PetId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PetId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PetId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PetId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqPetShowProto other) {
      if (other == null) {
        return;
      }
      if (other.PetId != 0) {
        PetId = other.PetId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PetId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回宠物模块信息		msgId=167101
  /// </summary>
  public sealed partial class ResPetInfoProto : pb::IMessage<ResPetInfoProto> {
    private static readonly pb::MessageParser<ResPetInfoProto> _parser = new pb::MessageParser<ResPetInfoProto>(() => new ResPetInfoProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResPetInfoProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResPetInfoProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResPetInfoProto(ResPetInfoProto other) : this() {
      pets_ = other.pets_.Clone();
      incubators_ = other.incubators_.Clone();
      showPetId_ = other.showPetId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResPetInfoProto Clone() {
      return new ResPetInfoProto(this);
    }

    /// <summary>Field number for the "pets" field.</summary>
    public const int PetsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Com.Proto.PetMessage.PetDtoProto> _repeated_pets_codec
        = pb::FieldCodec.ForMessage(10, global::Com.Proto.PetMessage.PetDtoProto.Parser);
    private readonly pbc::RepeatedField<global::Com.Proto.PetMessage.PetDtoProto> pets_ = new pbc::RepeatedField<global::Com.Proto.PetMessage.PetDtoProto>();
    /// <summary>
    ///宠物列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Proto.PetMessage.PetDtoProto> Pets {
      get { return pets_; }
    }

    /// <summary>Field number for the "incubators" field.</summary>
    public const int IncubatorsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Com.Proto.PetMessage.PetIncubatorDtoProto> _repeated_incubators_codec
        = pb::FieldCodec.ForMessage(18, global::Com.Proto.PetMessage.PetIncubatorDtoProto.Parser);
    private readonly pbc::RepeatedField<global::Com.Proto.PetMessage.PetIncubatorDtoProto> incubators_ = new pbc::RepeatedField<global::Com.Proto.PetMessage.PetIncubatorDtoProto>();
    /// <summary>
    ///孵蛋器列表(只含已解锁孵蛋器)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Proto.PetMessage.PetIncubatorDtoProto> Incubators {
      get { return incubators_; }
    }

    /// <summary>Field number for the "showPetId" field.</summary>
    public const int ShowPetIdFieldNumber = 3;
    private int showPetId_;
    /// <summary>
    ///显示的宠物id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ShowPetId {
      get { return showPetId_; }
      set {
        showPetId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResPetInfoProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResPetInfoProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!pets_.Equals(other.pets_)) return false;
      if(!incubators_.Equals(other.incubators_)) return false;
      if (ShowPetId != other.ShowPetId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= pets_.GetHashCode();
      hash ^= incubators_.GetHashCode();
      if (ShowPetId != 0) hash ^= ShowPetId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      pets_.WriteTo(output, _repeated_pets_codec);
      incubators_.WriteTo(output, _repeated_incubators_codec);
      if (ShowPetId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ShowPetId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += pets_.CalculateSize(_repeated_pets_codec);
      size += incubators_.CalculateSize(_repeated_incubators_codec);
      if (ShowPetId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ShowPetId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResPetInfoProto other) {
      if (other == null) {
        return;
      }
      pets_.Add(other.pets_);
      incubators_.Add(other.incubators_);
      if (other.ShowPetId != 0) {
        ShowPetId = other.ShowPetId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            pets_.AddEntriesFrom(input, _repeated_pets_codec);
            break;
          }
          case 18: {
            incubators_.AddEntriesFrom(input, _repeated_incubators_codec);
            break;
          }
          case 24: {
            ShowPetId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回宠物更新信息		msgId=167102
  /// </summary>
  public sealed partial class ResPetUpdateProto : pb::IMessage<ResPetUpdateProto> {
    private static readonly pb::MessageParser<ResPetUpdateProto> _parser = new pb::MessageParser<ResPetUpdateProto>(() => new ResPetUpdateProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResPetUpdateProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResPetUpdateProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResPetUpdateProto(ResPetUpdateProto other) : this() {
      pet_ = other.pet_ != null ? other.pet_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResPetUpdateProto Clone() {
      return new ResPetUpdateProto(this);
    }

    /// <summary>Field number for the "pet" field.</summary>
    public const int PetFieldNumber = 1;
    private global::Com.Proto.PetMessage.PetDtoProto pet_;
    /// <summary>
    ///宠物信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Proto.PetMessage.PetDtoProto Pet {
      get { return pet_; }
      set {
        pet_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResPetUpdateProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResPetUpdateProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Pet, other.Pet)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (pet_ != null) hash ^= Pet.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (pet_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Pet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (pet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pet);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResPetUpdateProto other) {
      if (other == null) {
        return;
      }
      if (other.pet_ != null) {
        if (pet_ == null) {
          Pet = new global::Com.Proto.PetMessage.PetDtoProto();
        }
        Pet.MergeFrom(other.Pet);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (pet_ == null) {
              Pet = new global::Com.Proto.PetMessage.PetDtoProto();
            }
            input.ReadMessage(Pet);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回孵蛋器更新信息		msgId=167103
  /// </summary>
  public sealed partial class ResPetIncubatorUpdateProto : pb::IMessage<ResPetIncubatorUpdateProto> {
    private static readonly pb::MessageParser<ResPetIncubatorUpdateProto> _parser = new pb::MessageParser<ResPetIncubatorUpdateProto>(() => new ResPetIncubatorUpdateProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResPetIncubatorUpdateProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResPetIncubatorUpdateProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResPetIncubatorUpdateProto(ResPetIncubatorUpdateProto other) : this() {
      incubators_ = other.incubators_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResPetIncubatorUpdateProto Clone() {
      return new ResPetIncubatorUpdateProto(this);
    }

    /// <summary>Field number for the "incubators" field.</summary>
    public const int IncubatorsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Com.Proto.PetMessage.PetIncubatorDtoProto> _repeated_incubators_codec
        = pb::FieldCodec.ForMessage(10, global::Com.Proto.PetMessage.PetIncubatorDtoProto.Parser);
    private readonly pbc::RepeatedField<global::Com.Proto.PetMessage.PetIncubatorDtoProto> incubators_ = new pbc::RepeatedField<global::Com.Proto.PetMessage.PetIncubatorDtoProto>();
    /// <summary>
    ///孵蛋器信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Proto.PetMessage.PetIncubatorDtoProto> Incubators {
      get { return incubators_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResPetIncubatorUpdateProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResPetIncubatorUpdateProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!incubators_.Equals(other.incubators_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= incubators_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      incubators_.WriteTo(output, _repeated_incubators_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += incubators_.CalculateSize(_repeated_incubators_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResPetIncubatorUpdateProto other) {
      if (other == null) {
        return;
      }
      incubators_.Add(other.incubators_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            incubators_.AddEntriesFrom(input, _repeated_incubators_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回重复获得宠物		msgId=167104
  /// </summary>
  public sealed partial class ResPetRepeatGainProto : pb::IMessage<ResPetRepeatGainProto> {
    private static readonly pb::MessageParser<ResPetRepeatGainProto> _parser = new pb::MessageParser<ResPetRepeatGainProto>(() => new ResPetRepeatGainProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResPetRepeatGainProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResPetRepeatGainProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResPetRepeatGainProto(ResPetRepeatGainProto other) : this() {
      petId_ = other.petId_;
      num_ = other.num_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResPetRepeatGainProto Clone() {
      return new ResPetRepeatGainProto(this);
    }

    /// <summary>Field number for the "petId" field.</summary>
    public const int PetIdFieldNumber = 1;
    private int petId_;
    /// <summary>
    ///重复的宠物id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PetId {
      get { return petId_; }
      set {
        petId_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 2;
    private int num_;
    /// <summary>
    ///重复数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResPetRepeatGainProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResPetRepeatGainProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PetId != other.PetId) return false;
      if (Num != other.Num) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PetId != 0) hash ^= PetId.GetHashCode();
      if (Num != 0) hash ^= Num.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PetId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PetId);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PetId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PetId);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResPetRepeatGainProto other) {
      if (other == null) {
        return;
      }
      if (other.PetId != 0) {
        PetId = other.PetId;
      }
      if (other.Num != 0) {
        Num = other.Num;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PetId = input.ReadInt32();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 宠物信息		msgId=167201
  /// </summary>
  public sealed partial class PetDtoProto : pb::IMessage<PetDtoProto> {
    private static readonly pb::MessageParser<PetDtoProto> _parser = new pb::MessageParser<PetDtoProto>(() => new PetDtoProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PetDtoProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PetDtoProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PetDtoProto(PetDtoProto other) : this() {
      petId_ = other.petId_;
      stage_ = other.stage_;
      level_ = other.level_;
      count_ = other.count_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PetDtoProto Clone() {
      return new PetDtoProto(this);
    }

    /// <summary>Field number for the "petId" field.</summary>
    public const int PetIdFieldNumber = 1;
    private int petId_;
    /// <summary>
    ///宠物id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PetId {
      get { return petId_; }
      set {
        petId_ = value;
      }
    }

    /// <summary>Field number for the "stage" field.</summary>
    public const int StageFieldNumber = 2;
    private int stage_;
    /// <summary>
    ///阶
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Stage {
      get { return stage_; }
      set {
        stage_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 3;
    private int level_;
    /// <summary>
    ///级
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 4;
    private int count_;
    /// <summary>
    ///相关计数器的值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PetDtoProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PetDtoProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PetId != other.PetId) return false;
      if (Stage != other.Stage) return false;
      if (Level != other.Level) return false;
      if (Count != other.Count) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PetId != 0) hash ^= PetId.GetHashCode();
      if (Stage != 0) hash ^= Stage.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Count != 0) hash ^= Count.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PetId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PetId);
      }
      if (Stage != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Stage);
      }
      if (Level != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Level);
      }
      if (Count != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PetId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PetId);
      }
      if (Stage != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Stage);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PetDtoProto other) {
      if (other == null) {
        return;
      }
      if (other.PetId != 0) {
        PetId = other.PetId;
      }
      if (other.Stage != 0) {
        Stage = other.Stage;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Count != 0) {
        Count = other.Count;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PetId = input.ReadInt32();
            break;
          }
          case 16: {
            Stage = input.ReadInt32();
            break;
          }
          case 24: {
            Level = input.ReadInt32();
            break;
          }
          case 32: {
            Count = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 宠物孵蛋器信息		msgId=167202
  /// </summary>
  public sealed partial class PetIncubatorDtoProto : pb::IMessage<PetIncubatorDtoProto> {
    private static readonly pb::MessageParser<PetIncubatorDtoProto> _parser = new pb::MessageParser<PetIncubatorDtoProto>(() => new PetIncubatorDtoProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PetIncubatorDtoProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.PetMessage.PetReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PetIncubatorDtoProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PetIncubatorDtoProto(PetIncubatorDtoProto other) : this() {
      incubatorId_ = other.incubatorId_;
      eggId_ = other.eggId_;
      startTime_ = other.startTime_;
      endTime_ = other.endTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PetIncubatorDtoProto Clone() {
      return new PetIncubatorDtoProto(this);
    }

    /// <summary>Field number for the "incubatorId" field.</summary>
    public const int IncubatorIdFieldNumber = 1;
    private int incubatorId_;
    /// <summary>
    ///孵蛋器id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IncubatorId {
      get { return incubatorId_; }
      set {
        incubatorId_ = value;
      }
    }

    /// <summary>Field number for the "eggId" field.</summary>
    public const int EggIdFieldNumber = 2;
    private int eggId_;
    /// <summary>
    ///蛋id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EggId {
      get { return eggId_; }
      set {
        eggId_ = value;
      }
    }

    /// <summary>Field number for the "startTime" field.</summary>
    public const int StartTimeFieldNumber = 3;
    private int startTime_;
    /// <summary>
    ///开始孵蛋时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "endTime" field.</summary>
    public const int EndTimeFieldNumber = 4;
    private int endTime_;
    /// <summary>
    ///结束孵蛋时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PetIncubatorDtoProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PetIncubatorDtoProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IncubatorId != other.IncubatorId) return false;
      if (EggId != other.EggId) return false;
      if (StartTime != other.StartTime) return false;
      if (EndTime != other.EndTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IncubatorId != 0) hash ^= IncubatorId.GetHashCode();
      if (EggId != 0) hash ^= EggId.GetHashCode();
      if (StartTime != 0) hash ^= StartTime.GetHashCode();
      if (EndTime != 0) hash ^= EndTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IncubatorId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IncubatorId);
      }
      if (EggId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EggId);
      }
      if (StartTime != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(StartTime);
      }
      if (EndTime != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(EndTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IncubatorId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IncubatorId);
      }
      if (EggId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EggId);
      }
      if (StartTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartTime);
      }
      if (EndTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EndTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PetIncubatorDtoProto other) {
      if (other == null) {
        return;
      }
      if (other.IncubatorId != 0) {
        IncubatorId = other.IncubatorId;
      }
      if (other.EggId != 0) {
        EggId = other.EggId;
      }
      if (other.StartTime != 0) {
        StartTime = other.StartTime;
      }
      if (other.EndTime != 0) {
        EndTime = other.EndTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IncubatorId = input.ReadInt32();
            break;
          }
          case 16: {
            EggId = input.ReadInt32();
            break;
          }
          case 24: {
            StartTime = input.ReadInt32();
            break;
          }
          case 32: {
            EndTime = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
