// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: topic.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Proto.TopicMessage {

  /// <summary>Holder for reflection information generated from topic.proto</summary>
  public static partial class TopicReflection {

    #region Descriptor
    /// <summary>File descriptor for topic.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TopicReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgt0b3BpYy5wcm90bxIWY29tLnByb3RvLnRvcGljTWVzc2FnZRoOcmVzb3Vy",
            "Y2UucHJvdG8iRwoUVG9waWNDb250ZW50RHRvUHJvdG8SDwoHdG9waWNJZBgB",
            "IAEoBRIMCgR0aW1lGAIgASgFEhAKCGNvbnRlbnRzGAMgAygFIigKEVJlcVRv",
            "cGljSW5mb1Byb3RvEhMKC2NvbmZpZGFudElkGAEgASgFIkkKD1JlcVRhbGtp",
            "bmdQcm90bxITCgtjb25maWRhbnRJZBgBIAEoBRIPCgd0b3BpY0lkGAIgASgF",
            "EhAKCGNob29zZUlkGAMgASgFIkYKDVJlcVJlcGx5UHJvdG8SEwoLY29uZmlk",
            "YW50SWQYASABKAUSDwoHdG9waWNJZBgCIAEoBRIPCgdyZXBseUlkGAMgASgF",
            "IlMKGlJlcVJlc2V0SGlzdG9yeVJlY29yZFByb3RvEhMKC2NvbmZpZGFudElk",
            "GAEgASgFEg8KB3RvcGljSWQYAiABKAUSDwoHY2hvb3NlcxgDIAMoBSLaAQoR",
            "UmVzVG9waWNJbmZvUHJvdG8SQgoMY3VycmVudFRvcGljGAEgASgLMiwuY29t",
            "LnByb3RvLnRvcGljTWVzc2FnZS5Ub3BpY0NvbnRlbnREdG9Qcm90bxI9Cgdt",
            "YWlsYm94GAIgAygLMiwuY29tLnByb3RvLnRvcGljTWVzc2FnZS5Ub3BpY0Nv",
            "bnRlbnREdG9Qcm90bxJCCgxoaXN0b3J5VG9waWMYAyADKAsyLC5jb20ucHJv",
            "dG8udG9waWNNZXNzYWdlLlRvcGljQ29udGVudER0b1Byb3RvIp8BCg9SZXNU",
            "YWxraW5nUHJvdG8SPgoGcmV3YXJkGAEgASgLMi4uY29tLnByb3RvLnJlc291",
            "cmNlTWVzc2FnZS5SZXdhcmRHcm91cER0b1Byb3RvEj4KCG5leHRUYWxrGAIg",
            "ASgLMiwuY29tLnByb3RvLnRvcGljTWVzc2FnZS5Ub3BpY0NvbnRlbnREdG9Q",
            "cm90bxIMCgRvdmVyGAMgASgIIl0KDVJlc1JlcGx5UHJvdG8SPgoGcmV3YXJk",
            "GAEgASgLMi4uY29tLnByb3RvLnJlc291cmNlTWVzc2FnZS5SZXdhcmRHcm91",
            "cER0b1Byb3RvEgwKBG92ZXIYAiABKAgiLQoaUmVzUmVzZXRIaXN0b3J5UmVj",
            "b3JkUHJvdG8SDwoHdG9waWNJZBgBIAEoBSI7ChNSZXNBZGROZXdUb3BpY1By",
            "b3RvEhMKC2NvbmZpZGFudElkGAEgASgFEg8KB3RvcGljSWQYAiABKAVCLQoe",
            "Y29tLmdhbWUubW9kdWxlLnRvcGljLnByb3RvY29sQgtUb3BpY1Byb3Rvc2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Com.Proto.ResourceMessage.ResourceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.TopicMessage.TopicContentDtoProto), global::Com.Proto.TopicMessage.TopicContentDtoProto.Parser, new[]{ "TopicId", "Time", "Contents" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.TopicMessage.ReqTopicInfoProto), global::Com.Proto.TopicMessage.ReqTopicInfoProto.Parser, new[]{ "ConfidantId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.TopicMessage.ReqTalkingProto), global::Com.Proto.TopicMessage.ReqTalkingProto.Parser, new[]{ "ConfidantId", "TopicId", "ChooseId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.TopicMessage.ReqReplyProto), global::Com.Proto.TopicMessage.ReqReplyProto.Parser, new[]{ "ConfidantId", "TopicId", "ReplyId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.TopicMessage.ReqResetHistoryRecordProto), global::Com.Proto.TopicMessage.ReqResetHistoryRecordProto.Parser, new[]{ "ConfidantId", "TopicId", "Chooses" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.TopicMessage.ResTopicInfoProto), global::Com.Proto.TopicMessage.ResTopicInfoProto.Parser, new[]{ "CurrentTopic", "Mailbox", "HistoryTopic" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.TopicMessage.ResTalkingProto), global::Com.Proto.TopicMessage.ResTalkingProto.Parser, new[]{ "Reward", "NextTalk", "Over" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.TopicMessage.ResReplyProto), global::Com.Proto.TopicMessage.ResReplyProto.Parser, new[]{ "Reward", "Over" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.TopicMessage.ResResetHistoryRecordProto), global::Com.Proto.TopicMessage.ResResetHistoryRecordProto.Parser, new[]{ "TopicId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.TopicMessage.ResAddNewTopicProto), global::Com.Proto.TopicMessage.ResAddNewTopicProto.Parser, new[]{ "ConfidantId", "TopicId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 协议列表
  /// 话题内容		msgId=160001
  /// </summary>
  public sealed partial class TopicContentDtoProto : pb::IMessage<TopicContentDtoProto> {
    private static readonly pb::MessageParser<TopicContentDtoProto> _parser = new pb::MessageParser<TopicContentDtoProto>(() => new TopicContentDtoProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TopicContentDtoProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.TopicMessage.TopicReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TopicContentDtoProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TopicContentDtoProto(TopicContentDtoProto other) : this() {
      topicId_ = other.topicId_;
      time_ = other.time_;
      contents_ = other.contents_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TopicContentDtoProto Clone() {
      return new TopicContentDtoProto(this);
    }

    /// <summary>Field number for the "topicId" field.</summary>
    public const int TopicIdFieldNumber = 1;
    private int topicId_;
    /// <summary>
    ///话题 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TopicId {
      get { return topicId_; }
      set {
        topicId_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 2;
    private int time_;
    /// <summary>
    ///获得时间 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "contents" field.</summary>
    public const int ContentsFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_contents_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> contents_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///内容列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Contents {
      get { return contents_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TopicContentDtoProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TopicContentDtoProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TopicId != other.TopicId) return false;
      if (Time != other.Time) return false;
      if(!contents_.Equals(other.contents_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TopicId != 0) hash ^= TopicId.GetHashCode();
      if (Time != 0) hash ^= Time.GetHashCode();
      hash ^= contents_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TopicId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TopicId);
      }
      if (Time != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Time);
      }
      contents_.WriteTo(output, _repeated_contents_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TopicId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TopicId);
      }
      if (Time != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
      }
      size += contents_.CalculateSize(_repeated_contents_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TopicContentDtoProto other) {
      if (other == null) {
        return;
      }
      if (other.TopicId != 0) {
        TopicId = other.TopicId;
      }
      if (other.Time != 0) {
        Time = other.Time;
      }
      contents_.Add(other.contents_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TopicId = input.ReadInt32();
            break;
          }
          case 16: {
            Time = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            contents_.AddEntriesFrom(input, _repeated_contents_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 请求话题信息		msgId=160101
  /// </summary>
  public sealed partial class ReqTopicInfoProto : pb::IMessage<ReqTopicInfoProto> {
    private static readonly pb::MessageParser<ReqTopicInfoProto> _parser = new pb::MessageParser<ReqTopicInfoProto>(() => new ReqTopicInfoProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqTopicInfoProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.TopicMessage.TopicReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTopicInfoProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTopicInfoProto(ReqTopicInfoProto other) : this() {
      confidantId_ = other.confidantId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTopicInfoProto Clone() {
      return new ReqTopicInfoProto(this);
    }

    /// <summary>Field number for the "confidantId" field.</summary>
    public const int ConfidantIdFieldNumber = 1;
    private int confidantId_;
    /// <summary>
    ///知己 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConfidantId {
      get { return confidantId_; }
      set {
        confidantId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqTopicInfoProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqTopicInfoProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ConfidantId != other.ConfidantId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ConfidantId != 0) hash ^= ConfidantId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ConfidantId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ConfidantId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ConfidantId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConfidantId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqTopicInfoProto other) {
      if (other == null) {
        return;
      }
      if (other.ConfidantId != 0) {
        ConfidantId = other.ConfidantId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ConfidantId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 对话		msgId=160102
  /// </summary>
  public sealed partial class ReqTalkingProto : pb::IMessage<ReqTalkingProto> {
    private static readonly pb::MessageParser<ReqTalkingProto> _parser = new pb::MessageParser<ReqTalkingProto>(() => new ReqTalkingProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqTalkingProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.TopicMessage.TopicReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTalkingProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTalkingProto(ReqTalkingProto other) : this() {
      confidantId_ = other.confidantId_;
      topicId_ = other.topicId_;
      chooseId_ = other.chooseId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTalkingProto Clone() {
      return new ReqTalkingProto(this);
    }

    /// <summary>Field number for the "confidantId" field.</summary>
    public const int ConfidantIdFieldNumber = 1;
    private int confidantId_;
    /// <summary>
    ///知己 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConfidantId {
      get { return confidantId_; }
      set {
        confidantId_ = value;
      }
    }

    /// <summary>Field number for the "topicId" field.</summary>
    public const int TopicIdFieldNumber = 2;
    private int topicId_;
    /// <summary>
    ///话题 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TopicId {
      get { return topicId_; }
      set {
        topicId_ = value;
      }
    }

    /// <summary>Field number for the "chooseId" field.</summary>
    public const int ChooseIdFieldNumber = 3;
    private int chooseId_;
    /// <summary>
    ///选择 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChooseId {
      get { return chooseId_; }
      set {
        chooseId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqTalkingProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqTalkingProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ConfidantId != other.ConfidantId) return false;
      if (TopicId != other.TopicId) return false;
      if (ChooseId != other.ChooseId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ConfidantId != 0) hash ^= ConfidantId.GetHashCode();
      if (TopicId != 0) hash ^= TopicId.GetHashCode();
      if (ChooseId != 0) hash ^= ChooseId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ConfidantId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ConfidantId);
      }
      if (TopicId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TopicId);
      }
      if (ChooseId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ChooseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ConfidantId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConfidantId);
      }
      if (TopicId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TopicId);
      }
      if (ChooseId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChooseId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqTalkingProto other) {
      if (other == null) {
        return;
      }
      if (other.ConfidantId != 0) {
        ConfidantId = other.ConfidantId;
      }
      if (other.TopicId != 0) {
        TopicId = other.TopicId;
      }
      if (other.ChooseId != 0) {
        ChooseId = other.ChooseId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ConfidantId = input.ReadInt32();
            break;
          }
          case 16: {
            TopicId = input.ReadInt32();
            break;
          }
          case 24: {
            ChooseId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 回信		msgId=160103
  /// </summary>
  public sealed partial class ReqReplyProto : pb::IMessage<ReqReplyProto> {
    private static readonly pb::MessageParser<ReqReplyProto> _parser = new pb::MessageParser<ReqReplyProto>(() => new ReqReplyProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqReplyProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.TopicMessage.TopicReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqReplyProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqReplyProto(ReqReplyProto other) : this() {
      confidantId_ = other.confidantId_;
      topicId_ = other.topicId_;
      replyId_ = other.replyId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqReplyProto Clone() {
      return new ReqReplyProto(this);
    }

    /// <summary>Field number for the "confidantId" field.</summary>
    public const int ConfidantIdFieldNumber = 1;
    private int confidantId_;
    /// <summary>
    ///知己 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConfidantId {
      get { return confidantId_; }
      set {
        confidantId_ = value;
      }
    }

    /// <summary>Field number for the "topicId" field.</summary>
    public const int TopicIdFieldNumber = 2;
    private int topicId_;
    /// <summary>
    ///话题 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TopicId {
      get { return topicId_; }
      set {
        topicId_ = value;
      }
    }

    /// <summary>Field number for the "replyId" field.</summary>
    public const int ReplyIdFieldNumber = 3;
    private int replyId_;
    /// <summary>
    ///回信 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ReplyId {
      get { return replyId_; }
      set {
        replyId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqReplyProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqReplyProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ConfidantId != other.ConfidantId) return false;
      if (TopicId != other.TopicId) return false;
      if (ReplyId != other.ReplyId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ConfidantId != 0) hash ^= ConfidantId.GetHashCode();
      if (TopicId != 0) hash ^= TopicId.GetHashCode();
      if (ReplyId != 0) hash ^= ReplyId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ConfidantId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ConfidantId);
      }
      if (TopicId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TopicId);
      }
      if (ReplyId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ReplyId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ConfidantId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConfidantId);
      }
      if (TopicId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TopicId);
      }
      if (ReplyId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReplyId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqReplyProto other) {
      if (other == null) {
        return;
      }
      if (other.ConfidantId != 0) {
        ConfidantId = other.ConfidantId;
      }
      if (other.TopicId != 0) {
        TopicId = other.TopicId;
      }
      if (other.ReplyId != 0) {
        ReplyId = other.ReplyId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ConfidantId = input.ReadInt32();
            break;
          }
          case 16: {
            TopicId = input.ReadInt32();
            break;
          }
          case 24: {
            ReplyId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 重置历史话题		msgId=160104
  /// </summary>
  public sealed partial class ReqResetHistoryRecordProto : pb::IMessage<ReqResetHistoryRecordProto> {
    private static readonly pb::MessageParser<ReqResetHistoryRecordProto> _parser = new pb::MessageParser<ReqResetHistoryRecordProto>(() => new ReqResetHistoryRecordProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqResetHistoryRecordProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.TopicMessage.TopicReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqResetHistoryRecordProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqResetHistoryRecordProto(ReqResetHistoryRecordProto other) : this() {
      confidantId_ = other.confidantId_;
      topicId_ = other.topicId_;
      chooses_ = other.chooses_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqResetHistoryRecordProto Clone() {
      return new ReqResetHistoryRecordProto(this);
    }

    /// <summary>Field number for the "confidantId" field.</summary>
    public const int ConfidantIdFieldNumber = 1;
    private int confidantId_;
    /// <summary>
    ///知己 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConfidantId {
      get { return confidantId_; }
      set {
        confidantId_ = value;
      }
    }

    /// <summary>Field number for the "topicId" field.</summary>
    public const int TopicIdFieldNumber = 2;
    private int topicId_;
    /// <summary>
    ///话题 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TopicId {
      get { return topicId_; }
      set {
        topicId_ = value;
      }
    }

    /// <summary>Field number for the "chooses" field.</summary>
    public const int ChoosesFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_chooses_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> chooses_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///重置之后的完整选项列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Chooses {
      get { return chooses_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqResetHistoryRecordProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqResetHistoryRecordProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ConfidantId != other.ConfidantId) return false;
      if (TopicId != other.TopicId) return false;
      if(!chooses_.Equals(other.chooses_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ConfidantId != 0) hash ^= ConfidantId.GetHashCode();
      if (TopicId != 0) hash ^= TopicId.GetHashCode();
      hash ^= chooses_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ConfidantId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ConfidantId);
      }
      if (TopicId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TopicId);
      }
      chooses_.WriteTo(output, _repeated_chooses_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ConfidantId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConfidantId);
      }
      if (TopicId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TopicId);
      }
      size += chooses_.CalculateSize(_repeated_chooses_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqResetHistoryRecordProto other) {
      if (other == null) {
        return;
      }
      if (other.ConfidantId != 0) {
        ConfidantId = other.ConfidantId;
      }
      if (other.TopicId != 0) {
        TopicId = other.TopicId;
      }
      chooses_.Add(other.chooses_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ConfidantId = input.ReadInt32();
            break;
          }
          case 16: {
            TopicId = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            chooses_.AddEntriesFrom(input, _repeated_chooses_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回知己信息		msgId=160201
  /// </summary>
  public sealed partial class ResTopicInfoProto : pb::IMessage<ResTopicInfoProto> {
    private static readonly pb::MessageParser<ResTopicInfoProto> _parser = new pb::MessageParser<ResTopicInfoProto>(() => new ResTopicInfoProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResTopicInfoProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.TopicMessage.TopicReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResTopicInfoProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResTopicInfoProto(ResTopicInfoProto other) : this() {
      currentTopic_ = other.currentTopic_ != null ? other.currentTopic_.Clone() : null;
      mailbox_ = other.mailbox_.Clone();
      historyTopic_ = other.historyTopic_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResTopicInfoProto Clone() {
      return new ResTopicInfoProto(this);
    }

    /// <summary>Field number for the "currentTopic" field.</summary>
    public const int CurrentTopicFieldNumber = 1;
    private global::Com.Proto.TopicMessage.TopicContentDtoProto currentTopic_;
    /// <summary>
    ///当前话题
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Proto.TopicMessage.TopicContentDtoProto CurrentTopic {
      get { return currentTopic_; }
      set {
        currentTopic_ = value;
      }
    }

    /// <summary>Field number for the "mailbox" field.</summary>
    public const int MailboxFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Com.Proto.TopicMessage.TopicContentDtoProto> _repeated_mailbox_codec
        = pb::FieldCodec.ForMessage(18, global::Com.Proto.TopicMessage.TopicContentDtoProto.Parser);
    private readonly pbc::RepeatedField<global::Com.Proto.TopicMessage.TopicContentDtoProto> mailbox_ = new pbc::RepeatedField<global::Com.Proto.TopicMessage.TopicContentDtoProto>();
    /// <summary>
    ///信箱
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Proto.TopicMessage.TopicContentDtoProto> Mailbox {
      get { return mailbox_; }
    }

    /// <summary>Field number for the "historyTopic" field.</summary>
    public const int HistoryTopicFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Com.Proto.TopicMessage.TopicContentDtoProto> _repeated_historyTopic_codec
        = pb::FieldCodec.ForMessage(26, global::Com.Proto.TopicMessage.TopicContentDtoProto.Parser);
    private readonly pbc::RepeatedField<global::Com.Proto.TopicMessage.TopicContentDtoProto> historyTopic_ = new pbc::RepeatedField<global::Com.Proto.TopicMessage.TopicContentDtoProto>();
    /// <summary>
    ///历史话题
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Proto.TopicMessage.TopicContentDtoProto> HistoryTopic {
      get { return historyTopic_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResTopicInfoProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResTopicInfoProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CurrentTopic, other.CurrentTopic)) return false;
      if(!mailbox_.Equals(other.mailbox_)) return false;
      if(!historyTopic_.Equals(other.historyTopic_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (currentTopic_ != null) hash ^= CurrentTopic.GetHashCode();
      hash ^= mailbox_.GetHashCode();
      hash ^= historyTopic_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (currentTopic_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrentTopic);
      }
      mailbox_.WriteTo(output, _repeated_mailbox_codec);
      historyTopic_.WriteTo(output, _repeated_historyTopic_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (currentTopic_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrentTopic);
      }
      size += mailbox_.CalculateSize(_repeated_mailbox_codec);
      size += historyTopic_.CalculateSize(_repeated_historyTopic_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResTopicInfoProto other) {
      if (other == null) {
        return;
      }
      if (other.currentTopic_ != null) {
        if (currentTopic_ == null) {
          CurrentTopic = new global::Com.Proto.TopicMessage.TopicContentDtoProto();
        }
        CurrentTopic.MergeFrom(other.CurrentTopic);
      }
      mailbox_.Add(other.mailbox_);
      historyTopic_.Add(other.historyTopic_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (currentTopic_ == null) {
              CurrentTopic = new global::Com.Proto.TopicMessage.TopicContentDtoProto();
            }
            input.ReadMessage(CurrentTopic);
            break;
          }
          case 18: {
            mailbox_.AddEntriesFrom(input, _repeated_mailbox_codec);
            break;
          }
          case 26: {
            historyTopic_.AddEntriesFrom(input, _repeated_historyTopic_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 收到谈话信息		msgId=160202
  /// </summary>
  public sealed partial class ResTalkingProto : pb::IMessage<ResTalkingProto> {
    private static readonly pb::MessageParser<ResTalkingProto> _parser = new pb::MessageParser<ResTalkingProto>(() => new ResTalkingProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResTalkingProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.TopicMessage.TopicReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResTalkingProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResTalkingProto(ResTalkingProto other) : this() {
      reward_ = other.reward_ != null ? other.reward_.Clone() : null;
      nextTalk_ = other.nextTalk_ != null ? other.nextTalk_.Clone() : null;
      over_ = other.over_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResTalkingProto Clone() {
      return new ResTalkingProto(this);
    }

    /// <summary>Field number for the "reward" field.</summary>
    public const int RewardFieldNumber = 1;
    private global::Com.Proto.ResourceMessage.RewardGroupDtoProto reward_;
    /// <summary>
    ///选项奖励
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Proto.ResourceMessage.RewardGroupDtoProto Reward {
      get { return reward_; }
      set {
        reward_ = value;
      }
    }

    /// <summary>Field number for the "nextTalk" field.</summary>
    public const int NextTalkFieldNumber = 2;
    private global::Com.Proto.TopicMessage.TopicContentDtoProto nextTalk_;
    /// <summary>
    ///下一个对话，可能为空,只有结束时，才会发
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Proto.TopicMessage.TopicContentDtoProto NextTalk {
      get { return nextTalk_; }
      set {
        nextTalk_ = value;
      }
    }

    /// <summary>Field number for the "over" field.</summary>
    public const int OverFieldNumber = 3;
    private bool over_;
    /// <summary>
    ///对话是否结束
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Over {
      get { return over_; }
      set {
        over_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResTalkingProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResTalkingProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Reward, other.Reward)) return false;
      if (!object.Equals(NextTalk, other.NextTalk)) return false;
      if (Over != other.Over) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (reward_ != null) hash ^= Reward.GetHashCode();
      if (nextTalk_ != null) hash ^= NextTalk.GetHashCode();
      if (Over != false) hash ^= Over.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (reward_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Reward);
      }
      if (nextTalk_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(NextTalk);
      }
      if (Over != false) {
        output.WriteRawTag(24);
        output.WriteBool(Over);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (reward_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reward);
      }
      if (nextTalk_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NextTalk);
      }
      if (Over != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResTalkingProto other) {
      if (other == null) {
        return;
      }
      if (other.reward_ != null) {
        if (reward_ == null) {
          Reward = new global::Com.Proto.ResourceMessage.RewardGroupDtoProto();
        }
        Reward.MergeFrom(other.Reward);
      }
      if (other.nextTalk_ != null) {
        if (nextTalk_ == null) {
          NextTalk = new global::Com.Proto.TopicMessage.TopicContentDtoProto();
        }
        NextTalk.MergeFrom(other.NextTalk);
      }
      if (other.Over != false) {
        Over = other.Over;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (reward_ == null) {
              Reward = new global::Com.Proto.ResourceMessage.RewardGroupDtoProto();
            }
            input.ReadMessage(Reward);
            break;
          }
          case 18: {
            if (nextTalk_ == null) {
              NextTalk = new global::Com.Proto.TopicMessage.TopicContentDtoProto();
            }
            input.ReadMessage(NextTalk);
            break;
          }
          case 24: {
            Over = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 收到回信		msgId=160203
  /// </summary>
  public sealed partial class ResReplyProto : pb::IMessage<ResReplyProto> {
    private static readonly pb::MessageParser<ResReplyProto> _parser = new pb::MessageParser<ResReplyProto>(() => new ResReplyProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResReplyProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.TopicMessage.TopicReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResReplyProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResReplyProto(ResReplyProto other) : this() {
      reward_ = other.reward_ != null ? other.reward_.Clone() : null;
      over_ = other.over_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResReplyProto Clone() {
      return new ResReplyProto(this);
    }

    /// <summary>Field number for the "reward" field.</summary>
    public const int RewardFieldNumber = 1;
    private global::Com.Proto.ResourceMessage.RewardGroupDtoProto reward_;
    /// <summary>
    ///选项奖励
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Proto.ResourceMessage.RewardGroupDtoProto Reward {
      get { return reward_; }
      set {
        reward_ = value;
      }
    }

    /// <summary>Field number for the "over" field.</summary>
    public const int OverFieldNumber = 2;
    private bool over_;
    /// <summary>
    ///回信是否结束
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Over {
      get { return over_; }
      set {
        over_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResReplyProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResReplyProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Reward, other.Reward)) return false;
      if (Over != other.Over) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (reward_ != null) hash ^= Reward.GetHashCode();
      if (Over != false) hash ^= Over.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (reward_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Reward);
      }
      if (Over != false) {
        output.WriteRawTag(16);
        output.WriteBool(Over);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (reward_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reward);
      }
      if (Over != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResReplyProto other) {
      if (other == null) {
        return;
      }
      if (other.reward_ != null) {
        if (reward_ == null) {
          Reward = new global::Com.Proto.ResourceMessage.RewardGroupDtoProto();
        }
        Reward.MergeFrom(other.Reward);
      }
      if (other.Over != false) {
        Over = other.Over;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (reward_ == null) {
              Reward = new global::Com.Proto.ResourceMessage.RewardGroupDtoProto();
            }
            input.ReadMessage(Reward);
            break;
          }
          case 16: {
            Over = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 返回重置结果		msgId=160204
  /// </summary>
  public sealed partial class ResResetHistoryRecordProto : pb::IMessage<ResResetHistoryRecordProto> {
    private static readonly pb::MessageParser<ResResetHistoryRecordProto> _parser = new pb::MessageParser<ResResetHistoryRecordProto>(() => new ResResetHistoryRecordProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResResetHistoryRecordProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.TopicMessage.TopicReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResResetHistoryRecordProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResResetHistoryRecordProto(ResResetHistoryRecordProto other) : this() {
      topicId_ = other.topicId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResResetHistoryRecordProto Clone() {
      return new ResResetHistoryRecordProto(this);
    }

    /// <summary>Field number for the "topicId" field.</summary>
    public const int TopicIdFieldNumber = 1;
    private int topicId_;
    /// <summary>
    ///话题 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TopicId {
      get { return topicId_; }
      set {
        topicId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResResetHistoryRecordProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResResetHistoryRecordProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TopicId != other.TopicId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TopicId != 0) hash ^= TopicId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TopicId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TopicId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TopicId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TopicId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResResetHistoryRecordProto other) {
      if (other == null) {
        return;
      }
      if (other.TopicId != 0) {
        TopicId = other.TopicId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TopicId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 收到新话题		msgId=160205
  /// </summary>
  public sealed partial class ResAddNewTopicProto : pb::IMessage<ResAddNewTopicProto> {
    private static readonly pb::MessageParser<ResAddNewTopicProto> _parser = new pb::MessageParser<ResAddNewTopicProto>(() => new ResAddNewTopicProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResAddNewTopicProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.TopicMessage.TopicReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResAddNewTopicProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResAddNewTopicProto(ResAddNewTopicProto other) : this() {
      confidantId_ = other.confidantId_;
      topicId_ = other.topicId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResAddNewTopicProto Clone() {
      return new ResAddNewTopicProto(this);
    }

    /// <summary>Field number for the "confidantId" field.</summary>
    public const int ConfidantIdFieldNumber = 1;
    private int confidantId_;
    /// <summary>
    ///知己 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConfidantId {
      get { return confidantId_; }
      set {
        confidantId_ = value;
      }
    }

    /// <summary>Field number for the "topicId" field.</summary>
    public const int TopicIdFieldNumber = 2;
    private int topicId_;
    /// <summary>
    ///话题 id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TopicId {
      get { return topicId_; }
      set {
        topicId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResAddNewTopicProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResAddNewTopicProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ConfidantId != other.ConfidantId) return false;
      if (TopicId != other.TopicId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ConfidantId != 0) hash ^= ConfidantId.GetHashCode();
      if (TopicId != 0) hash ^= TopicId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ConfidantId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ConfidantId);
      }
      if (TopicId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TopicId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ConfidantId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConfidantId);
      }
      if (TopicId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TopicId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResAddNewTopicProto other) {
      if (other == null) {
        return;
      }
      if (other.ConfidantId != 0) {
        ConfidantId = other.ConfidantId;
      }
      if (other.TopicId != 0) {
        TopicId = other.TopicId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ConfidantId = input.ReadInt32();
            break;
          }
          case 16: {
            TopicId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
